import React, { useState, useRef } from 'react';
import { View, Text, Pressable, StyleSheet, TextInput, ScrollView, KeyboardAvoidingView, Platform } from 'react-native';
import { useRouter } from 'expo-router';
import { Layout } from '../components/Layout';
import { Container, Card, PageHeader, Button } from '../components/ui';
import { colors, typography, spacing } from '../theme';

interface Message {
  id: string;
  text: string;
  sender: 'user' | 'bot';
  lang?: 'en' | 'si' | 'ta';
}

export default function Component4Screen() {
  const router = useRouter();
  const [messages, setMessages] = useState<Message[]>([
    { id: '1', sender: 'bot', text: 'Hello! I am your Legal Guide. How can I assist you today with Sri Lankan law?', lang: 'en' },
    { id: '2', sender: 'bot', text: 'ආයුබෝවන්! මම ඔබේ නීති උපදේශකයා. ශ්‍රී ලංකාවේ නීතිය පිළිබඳව අද ඔබට මා උදවු කරන්නේ කෙසේද?', lang: 'si' },
    { id: '3', sender: 'bot', text: 'வணக்கம்! நான் உங்கள் சட்ட வழிகாட்டி. இலங்கைச் சட்டத்தில் இன்று நான் உங்களுக்கு எவ்வாறு உதவ முடியும்?', lang: 'ta' }
  ]);
  const [inputText, setInputText] = useState('');
  const [loading, setLoading] = useState(false);
  const scrollViewRef = useRef<ScrollView>(null);

  const handleSend = () => {
    if (!inputText.trim()) return;

    const userMsg: Message = { id: Date.now().toString(), text: inputText, sender: 'user' };
    setMessages(prev => [...prev, userMsg]);
    setInputText('');
    setLoading(true);

    // Mock bot response
    setTimeout(() => {
      const botMsg: Message = {
        id: (Date.now() + 1).toString(),
        sender: 'bot',
        text: 'This is a helpful response about your legal query. In a real system, this would be generated by an AI model trained on Sri Lankan statutes and case law.',
        lang: 'en'
      };
      setMessages(prev => [...prev, botMsg]);
      setLoading(false);
    }, 1000);
  };

  return (
    <Layout noPadding>
      <Container style={styles.fullContainer}>
        <PageHeader
          title="Public Legal Assistant"
          breadcrumb="Public Access → Multilingual Law Support"
        />

        <View style={styles.chatWrapper}>
          <Card style={styles.chatCard}>
            <ScrollView
              ref={scrollViewRef}
              style={styles.msgScroll}
              onContentSizeChange={() => scrollViewRef.current?.scrollToEnd({ animated: true })}
              contentContainerStyle={styles.msgContent}
            >
              {messages.map((m) => (
                <View key={m.id} style={[styles.msgBubble, m.sender === 'user' ? styles.userBubble : styles.botBubble]}>
                  {m.lang && <Text style={styles.langIndicator}>{m.lang.toUpperCase()}</Text>}
                  <Text style={[styles.msgText, m.sender === 'user' ? styles.userText : styles.botText]}>{m.text}</Text>
                </View>
              ))}
              {loading && (
                <View style={[styles.msgBubble, styles.botBubble]}>
                  <Text style={styles.botText}>Assistant is typing...</Text>
                </View>
              )}
            </ScrollView>

            <View style={styles.inputArea}>
              <TextInput
                style={styles.input}
                placeholder="Ask a legal question in English, Sinhala, or Tamil..."
                value={inputText}
                onChangeText={setInputText}
                onSubmitEditing={handleSend}
              />
              <Pressable onPress={handleSend} style={styles.sendBtn}>
                <Text style={styles.sendBtnText}>Send</Text>
              </Pressable>
            </View>
          </Card>

          <Card style={styles.infoSideCard}>
            <Text style={styles.sideTitle}>Help Topics</Text>
            <View style={styles.topicList}>
              <Pressable style={styles.topicItem} onPress={() => setInputText('How to file a police report?')}>
                <Text style={styles.topicText}>📝 How to file a police report?</Text>
              </Pressable>
              <Pressable style={styles.topicItem} onPress={() => setInputText('What is bail?')}>
                <Text style={styles.topicText}>⚖ What is bail?</Text>
              </Pressable>
              <Pressable style={styles.topicItem} onPress={() => setInputText('Fundamental rights in Sri Lanka')}>
                <Text style={styles.topicText}>📜 Fundamental rights</Text>
              </Pressable>
            </View>
            <Text style={styles.disclaimer}>
              Disclaimer: This AI chatbot provides general legal information, not professional legal advice.
            </Text>
          </Card>
        </View>
      </Container>
    </Layout>
  );
}

const styles = StyleSheet.create({
  fullContainer: { flex: 1, paddingVertical: spacing.lg },
  chatWrapper: {
    flexDirection: Platform.OS === 'web' ? 'row' : 'column',
    gap: spacing.lg,
    flex: 1
  },
  chatCard: {
    flex: 3,
    height: Platform.OS === 'web' ? 600 : 500,
    padding: 0,
    overflow: 'hidden'
  },
  infoSideCard: { flex: 1, padding: spacing.lg },
  msgScroll: { flex: 1, backgroundColor: '#F9FAFB' },
  msgContent: { padding: spacing.md },
  msgBubble: {
    maxWidth: '85%',
    padding: 12,
    borderRadius: 12,
    marginBottom: spacing.md,
  },
  botBubble: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  userBubble: {
    alignSelf: 'flex-end',
    backgroundColor: colors.primary,
  },
  msgText: { fontSize: 15, lineHeight: 22 },
  botText: { color: colors.textPrimary },
  userText: { color: '#FFFFFF' },
  langIndicator: {
    fontSize: 10,
    fontWeight: 'bold',
    color: colors.accent,
    marginBottom: 4,
    opacity: 0.8
  },
  inputArea: {
    flexDirection: 'row',
    padding: spacing.md,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    alignItems: 'center',
    gap: spacing.sm
  },
  input: {
    flex: 1,
    height: 48,
    backgroundColor: '#F3F4F6',
    borderRadius: 24,
    paddingHorizontal: 16,
    fontSize: 15,
    ...(Platform.OS === 'web' ? { outlineWidth: 0 } : {})
  },
  sendBtn: {
    backgroundColor: colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
  },
  sendBtnText: { color: '#FFFFFF', fontWeight: 'bold' },
  sideTitle: { fontSize: 18, fontWeight: 'bold', color: colors.primary, marginBottom: spacing.md },
  topicList: { gap: spacing.sm },
  topicItem: {
    padding: 12,
    backgroundColor: colors.bgSection,
    borderRadius: 8,
  },
  topicText: { fontSize: 14, color: colors.textPrimary },
  disclaimer: { fontSize: 11, color: colors.textMuted, marginTop: spacing.xl, fontStyle: 'italic' }
});
