"""
Substring gazetteer for mapping free-text offence locations to coarse dashboard regions.
Patterns with spaces or length >= 8: substring match on normalized text.
Shorter single-token patterns: matched with letter boundaries to avoid false hits (e.g. galle in magalle).
Sorted by pattern length descending when building the runtime list.
"""
from __future__ import annotations

import re
from typing import List, Tuple

# (pattern lowercase, canonical region). Order here is arbitrary; sorted at load.
REGION_PATTERN_ENTRIES: List[Tuple[str, str]] = [
    # ── Long phrases (Colombo metro & institutions) ─────────────────────────
    ("bandaranayake international airport", "Gampaha"),
    ("people's bank branch in ginthupitiya", "Colombo"),
    ("near the junction where jalashaya road and sri vajiragnana mawatha meet, maradana", "Colombo"),
    ("near the deceased's house in a paddy field, kadawata area", "Gampaha"),
    ("pesalai within the jurisdiction of the high court of mannar", "Mannar"),
    ("pondara watta estate, including the watchman's hut and surrounding area", "Monaragala"),
    ("sedawatta thudugala road area via kelaniya", "Gampaha"),
    ("wickramaseela madya maha vidyalaya, giriulla", "Kurunegala"),
    ("mattakkuliya, near a childrens", "Colombo"),
    ("hotel sancharina, wattala police area", "Gampaha"),
    ("katunayake airport", "Gampaha"),
    ("national rupavahini corporation", "Colombo"),
    ("sporting times betting center, first floor of a building", "Colombo"),
    ("ruby cinema hall, maradana", "Colombo"),
    ("thoppuwa junction, kochchikade", "Colombo"),
    ("pannala, morakalewaththa area", "Kurunegala"),
    ("waharaka, ruwanwella", "Kegalle"),
    ("marawila, keenakele molawaththa, mudukatuwa", "Puttalam"),
    ("kandana church road junction", "Gampaha"),
    ("batuwatta, ragama", "Gampaha"),
    ("giridara, kapugoda", "Gampaha"),
    ("horethuduwa, near chandrasekera ground and a timber mill", "Kalutara"),
    ("ulpathagama, hasalaka", "Badulla"),
    ("tawalama and akuressa", "Matara"),
    ("akkarajpattu and addalaichchenai", "Ampara"),
    ("kalawana, gold jewellery shop", "Ratnapura"),
    ("wadullawatte in the orugodawatte area", "Colombo"),
    ("keselwatta in katuwana police area", "Hambantota"),
    ("on an estate road in the bulathsinhala area", "Kalutara"),
    ("kirulapone, rasikwatta canal near ilma international school", "Colombo"),
    ("near a church on makola road, makola", "Gampaha"),
    ("kotadeniyawa bus station, near a closed boutique", "Gampaha"),
    ("ponnambalam vaneshwara kovil at kotahena", "Colombo"),
    ("ratmalana (sumangala mawatha / aththidiya road area)", "Colombo"),
    ("ambalantota, at the house of pw1", "Hambantota"),
    # ── Nuwara Eliya & hill country ─────────────────────────────────────────
    ("nuwaraeliya", "Nuwara Eliya"),
    ("nuwara eliya", "Nuwara Eliya"),
    ("nuwara-eliya", "Nuwara Eliya"),
    ("talawakele", "Nuwara Eliya"),
    ("maskeliya", "Nuwara Eliya"),
    ("ragala", "Nuwara Eliya"),
    ("hanguranketha", "Nuwara Eliya"),
    ("hatton", "Nuwara Eliya"),
    ("dikoya", "Nuwara Eliya"),
    ("lindula", "Nuwara Eliya"),
    ("agarapatana", "Nuwara Eliya"),
    ("kotmale", "Nuwara Eliya"),
    ("ginigathena", "Nuwara Eliya"),
    ("welimada", "Badulla"),
    ("bandarawela", "Badulla"),
    ("haputale", "Badulla"),
    ("passara", "Badulla"),
    ("mahiyanganaya", "Badulla"),
    ("haliela", "Badulla"),
    ("badulla", "Badulla"),
    ("sooriyawewa", "Hambantota"),
    ("lunugamvehera", "Hambantota"),
    ("sewanagala", "Monaragala"),
    ("kataragama", "Monaragala"),
    ("tissamaharama", "Hambantota"),
    ("thissamaharama", "Hambantota"),
    ("ambalantota", "Hambantota"),
    ("hambantota", "Hambantota"),
    ("tangalle", "Hambantota"),
    ("beliatta", "Hambantota"),
    ("kudawella", "Hambantota"),
    ("weeraketiya", "Hambantota"),
    ("agulgamuwa", "Hambantota"),
    ("bogahakumbura", "Badulla"),
    ("dikwella", "Matara"),
    ("devinuwara", "Matara"),
    ("weligama", "Matara"),
    ("hakmana", "Matara"),
    ("kamburupitiya", "Matara"),
    ("akuressa", "Matara"),
    ("ahangama", "Galle"),
    ("baddegama", "Galle"),
    ("bentota", "Galle"),
    ("hikkaduwa", "Galle"),
    ("unawatuna", "Galle"),
    ("talpe", "Galle"),
    ("kosgoda", "Galle"),
    ("kahaduwa", "Galle"),
    ("magalle", "Galle"),
    ("bataduwa", "Galle"),
    ("matara", "Matara"),
    ("galle", "Galle"),
    ("deniyaya", "Matara"),
    ("pitabeddara", "Matara"),
    ("malimbada", "Matara"),
    ("welipitiya", "Matara"),
    ("gandara", "Matara"),
    ("kamburugamuwa", "Matara"),
    # ── Colombo & suburbs ───────────────────────────────────────────────────
    ("sri jayawardenapura kotte", "Colombo"),
    ("jayawardenapura", "Colombo"),
    ("battaramulla", "Colombo"),
    ("ethulkotte", "Colombo"),
    ("maligawa road", "Colombo"),
    ("mount lavinia", "Colombo"),
    ("dehiwala", "Colombo"),
    ("wellawatte", "Colombo"),
    ("bambalapitiya", "Colombo"),
    ("kollupitiya", "Colombo"),
    ("colombo fort", "Colombo"),
    ("pettah", "Colombo"),
    ("maradana", "Colombo"),
    ("dematagoda", "Colombo"),
    ("grandpass", "Colombo"),
    ("grand pass", "Colombo"),
    ("kochchikade", "Colombo"),
    ("kotahena", "Colombo"),
    ("modera", "Colombo"),
    ("keselwatta", "Colombo"),
    ("thimbirigasyaya", "Colombo"),
    ("narahenpita", "Colombo"),
    ("kirulapone", "Colombo"),
    ("borella", "Colombo"),
    ("hultsdorf", "Colombo"),
    ("pamankada", "Colombo"),
    ("union place", "Colombo"),
    ("slave island", "Colombo"),
    ("cinnamon gardens", "Colombo"),
    ("armour street", "Colombo"),
    ("maligawatta", "Colombo"),
    ("maligawaththa", "Colombo"),
    ("stacepura", "Colombo"),
    ("stasepura", "Colombo"),
    ("welikada", "Colombo"),
    ("sedawatta", "Colombo"),
    ("orugodawatte", "Colombo"),
    ("wadullawatte", "Colombo"),
    ("kolonnawa", "Colombo"),
    ("wellampitiya", "Colombo"),
    ("peliyagoda", "Gampaha"),
    ("rajagiriya", "Colombo"),
    ("ratmalana", "Colombo"),
    ("thalahena", "Colombo"),
    ("nugegoda", "Colombo"),
    ("delkanda", "Colombo"),
    ("moratuwa", "Colombo"),
    ("homagama", "Colombo"),
    ("maharagama", "Colombo"),
    ("piliyandala", "Colombo"),
    ("godagama", "Colombo"),
    ("meegoda", "Colombo"),
    ("kaduwela", "Colombo"),
    ("hanwella", "Colombo"),
    ("boralesgamuwa", "Colombo"),
    ("mattakkuliya", "Colombo"),
    ("colombo", "Colombo"),
    ("ginthupitiya", "Colombo"),
    ("kohuwala", "Colombo"),
    ("kotte", "Colombo"),
    ("kolpity", "Colombo"),
    ("pamankada", "Colombo"),
    # ── Gampaha & Negombo corridor ──────────────────────────────────────────
    ("bandaranayake", "Gampaha"),
    ("katunayake", "Gampaha"),
    ("seeduwa", "Gampaha"),
    ("ja ela", "Gampaha"),
    ("jaela", "Gampaha"),
    ("minuwangoda", "Gampaha"),
    ("divulapitiya", "Gampaha"),
    ("mirigama", "Gampaha"),
    ("welisara", "Gampaha"),
    ("makola", "Gampaha"),
    ("kapugoda", "Gampaha"),
    ("kiribathgoda", "Gampaha"),
    ("kelaniya", "Gampaha"),
    ("kadawatha", "Gampaha"),
    ("kandana", "Gampaha"),
    ("ragama", "Gampaha"),
    ("wattala", "Gampaha"),
    ("mabole", "Gampaha"),
    ("kotadeniyawa", "Gampaha"),
    ("udugampola", "Gampaha"),
    ("nedungahahena", "Gampaha"),
    ("thekkawatte", "Colombo"),
    ("modarapiliwela", "Gampaha"),
    ("galagedara", "Kurunegala"),
    ("gampaha", "Gampaha"),
    ("negombo", "Negombo"),
    ("katukurunda", "Kalutara"),
    ("horana", "Kalutara"),
    ("ingiriya", "Kalutara"),
    ("bandaragama", "Kalutara"),
    ("bulathsinhala", "Kalutara"),
    ("mathugama", "Kalutara"),
    ("beruwala", "Kalutara"),
    ("aluthgama", "Kalutara"),
    ("dharga town", "Kalutara"),
    ("payagala", "Kalutara"),
    ("kalutara", "Kalutara"),
    ("kaluthara", "Kalutara"),
    ("panadura", "Panadura"),
    ("wadduwa", "Kalutara"),
    ("kahanavita", "Kalutara"),
    ("warakathenna", "Kegalle"),
    ("chilaw", "Chilaw"),
    ("madampe", "Chilaw"),
    ("nattandiya", "Chilaw"),
    ("dankotuwa", "Chilaw"),
    ("wennappuwa", "Chilaw"),
    ("nainamadama", "Puttalam"),
    ("mampuri", "Puttalam"),
    ("puttalam", "Puttalam"),
    ("marawila", "Puttalam"),
    ("saliyawewa", "Puttalam"),
    ("dunumadalawa", "Puttalam"),
    ("anamaduwa", "Puttalam"),
    ("kalpitiya", "Puttalam"),
    ("norochcholai", "Puttalam"),
    ("norochchole", "Puttalam"),
    ("palavi", "Puttalam"),
    ("thalawa", "Puttalam"),
    ("galinna", "Ratnapura"),
    ("rathnapura", "Ratnapura"),
    ("ratnapura", "Ratnapura"),
    ("kalawana", "Ratnapura"),
    ("balangoda", "Ratnapura"),
    ("godakawela", "Ratnapura"),
    ("kolonna", "Ratnapura"),
    ("embilipitiya", "Monaragala"),
    ("buttala", "Monaragala"),
    ("wellawaya", "Monaragala"),
    ("siyambalanduwa", "Monaragala"),
    ("monaragala", "Monaragala"),
    ("moneragala", "Monaragala"),
    ("kumbukkana", "Monaragala"),
    ("okkampitiya", "Monaragala"),
    ("galenbindunuwewa", "Polonnaruwa"),
    ("hingurakgoda", "Polonnaruwa"),
    ("medirigiriya", "Polonnaruwa"),
    ("polonnaruwa", "Polonnaruwa"),
    ("kekirawa", "Anuradhapura"),
    ("medawachchiya", "Anuradhapura"),
    ("galnewa", "Anuradhapura"),
    ("anuradhapura", "Anuradhapura"),
    ("amuradhapura", "Anuradhapura"),
    ("mihintale", "Anuradhapura"),
    ("tambuttegama", "Anuradhapura"),
    ("kalawewa", "Anuradhapura"),
    ("dambulla", "Matale"),
    ("galewela", "Matale"),
    ("wilgamuwa", "Matale"),
    ("rattota", "Matale"),
    ("ukuwela", "Matale"),
    ("palapathwela", "Matale"),
    ("matale", "Matale"),
    ("sigiriya", "Matale"),
    ("naula", "Matale"),
    ("gampola", "Kandy"),
    ("peradeniya", "Kandy"),
    ("teldeniya", "Kandy"),
    ("akurana", "Kandy"),
    ("katugastota", "Kandy"),
    ("kandy", "Kandy"),
    ("harispattuwa", "Kandy"),
    ("pathadumbara", "Kandy"),
    ("hasalaka", "Badulla"),
    ("kurunegala", "Kurunegala"),
    ("kurunagala", "Kurunegala"),
    ("kuliyapitiya", "Kurunegala"),
    ("mawathagama", "Kurunegala"),
    ("polgahawela", "Kurunegala"),
    ("giriulla", "Kurunegala"),
    ("nikaweratiya", "Kurunegala"),
    ("dambadeniya", "Kurunegala"),
    ("pannala", "Kurunegala"),
    ("ibbagamuwa", "Kurunegala"),
    ("alawwa", "Kurunegala"),
    ("wariyapola", "Kurunegala"),
    ("ganewatta", "Kurunegala"),
    ("galgamuwa", "Kurunegala"),
    ("kegalle", "Kegalle"),
    ("mawanella", "Kegalle"),
    ("mawanalla", "Kegalle"),
    ("warakapola", "Kegalle"),
    ("ruwanwella", "Kegalle"),
    ("deraniyagala", "Kegalle"),
    ("galigamuwa", "Kegalle"),
    ("kitulgala", "Kegalle"),
    ("yatiyanthota", "Kegalle"),
    ("dehiowita", "Kegalle"),
    ("hanepola", "Kurunegala"),
    ("kaldamulla", "Hambantota"),
    ("neliketiya", "Hambantota"),
    ("kiriyankalliya", "Puttalam"),
    ("samagama", "Ampara"),
    ("sisilasa gama", "Ampara"),
    ("oluvil", "Ampara"),
    ("sammanthurai", "Ampara"),
    ("pottuvil", "Ampara"),
    ("akkaraipattu", "Ampara"),
    ("addalaichenai", "Ampara"),
    ("addalaichchenai", "Ampara"),
    ("ninthavur", "Ampara"),
    ("kalmunai", "Kalmunai"),
    ("ampara", "Ampara"),
    ("eravur", "Batticaloa"),
    ("kattankudy", "Batticaloa"),
    ("kattankudi", "Batticaloa"),
    ("chenkalady", "Batticaloa"),
    ("valachchenai", "Batticaloa"),
    ("vakarai", "Batticaloa"),
    ("vaakarai", "Batticaloa"),
    ("batticaloa", "Batticaloa"),
    ("puttur", "Batticaloa"),
    ("trincomalee", "Trincomalee"),
    ("trinco", "Trincomalee"),
    ("kinniya", "Trincomalee"),
    ("mutur", "Trincomalee"),
    ("kuchchaveli", "Trincomalee"),
    ("mannar", "Mannar"),
    ("pesalai", "Mannar"),
    ("madhu", "Mannar"),
    ("talaimannar", "Mannar"),
    ("nanattan", "Mannar"),
    ("nanaddan", "Mannar"),
    ("vavuniya", "Vavuniya"),
    ("vavunia", "Vavuniya"),
    ("vauniya", "Vavuniya"),
    ("nedunkerny", "Vavuniya"),
    ("kilinochchi", "Kilinochchi"),
    ("paranthan", "Kilinochchi"),
    ("poonakary", "Kilinochchi"),
    ("palai", "Jaffna"),
    ("palali", "Jaffna"),
    ("jaffna", "Jaffna"),
    ("chunnakam", "Jaffna"),
    ("chavakachcheri", "Jaffna"),
    ("chavakacheri", "Jaffna"),
    ("point pedro", "Jaffna"),
    ("kopay", "Jaffna"),
    ("karainagar", "Jaffna"),
    ("kayts", "Jaffna"),
    ("sinnamadu", "Jaffna"),
    ("nelliyadi", "Jaffna"),
    ("tellipallai", "Jaffna"),
    ("sandilipay", "Jaffna"),
    ("uduvil", "Jaffna"),
    ("avissawella", "Avissawella"),
    ("awissawella", "Avissawella"),
    ("seethawaka", "Avissawella"),
    ("bharatipuram", "Mannar"),
    ("delmulla", "Ampara"),
    ("delft", "Jaffna"),
    ("naragala", "Badulla"),
    ("dikhetherma", "Monaragala"),
    ("dikkapitiya", "Monaragala"),
    ("sedawatha", "Colombo"),
    ("athurugiriya", "Colombo"),
    ("pepiliyana", "Colombo"),
    ("meetiyagoda", "Galle"),
    ("agulugalle", "Galle"),
    ("gallawila", "Kurunegala"),
    ("karawanella", "Kegalle"),
    ("koswatta", "Colombo"),
    ("katthankudi", "Batticaloa"),
    ("madhunagala", "Hambantota"),
    ("akurala", "Galle"),
    ("kahawatta", "Ratnapura"),
    ("palugaswewa", "Anuradhapura"),
    ("haldanduwana", "Gampaha"),
    ("modara", "Colombo"),
    ("kottaramulla", "Colombo"),
    ("ranorawa", "Polonnaruwa"),
]

# De-duplicate identical (pattern, label) pairs while preserving first label
_seen: set = set()
_REGION_UNIQUE: List[Tuple[str, str]] = []
for _pat, _lab in REGION_PATTERN_ENTRIES:
    _k = (_pat, _lab)
    if _k in _seen:
        continue
    _seen.add(_k)
    _REGION_UNIQUE.append((_pat, _lab))


def sorted_region_patterns() -> List[Tuple[str, str]]:
    return sorted(_REGION_UNIQUE, key=lambda x: (len(x[0]), len(x[0].replace(" ", "")), x[0]), reverse=True)


def region_pattern_match(norm: str, norm_compact: str, pattern: str) -> bool:
    """True if pattern matches in normalized location text."""
    if " " in pattern or len(pattern) >= 8:
        if pattern in norm:
            return True
        p0 = pattern.replace(" ", "")
        if p0 and p0 in norm_compact:
            return True
        return False
    esc = re.escape(pattern)
    return re.search(rf"(?<![a-z]){esc}(?![a-z])", norm, flags=re.IGNORECASE) is not None
